# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json]

locale: uk

ampscript:
  gastring: "?%%=v(@gaString)=%%"
  emailaddr: "%%emailaddr%%"
  view-online: "%%view_email_url%%"

# Partner
partner:
  # name: Partner Name
  # link: "#partner-link"
  # logo-width: 110


# image: "img/" # local
# image: "http://image.email.secretescapes.com/lib/fe91127277660c7b71/m/8" # remote