# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, bower_components, bower.json, README.md]
url-tracking: "?%%=v(@gaString)=%%"

# image-url: img/
image-url: http://image.email.secretescapes.com/lib/fe91127277660c7b71/m/8/
image-prefix: templateMM

client:
  name: Partner Name
  link: "#partner-link"

logo:
  black: logo.png
  white: logo-wh.png
  width: 110

combined-logo:
  alt: Partner Name & Secret Escapes Logos
  width: 264
  link: "#combined-link"