# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json]


# CLIENT
client:
  name: Partner Name
  link: "#partner-link"

logo:
  black: logo.png
  white: logo-wh.png
  width: 110

combined-logo:
  alt: Partner Name & Secret Escapes Logos
  width: 264
  link: "#combined-link"